### PR TITLE
Use walkDecls instead of eachDecl

### PR DESCRIPTION
**Pull request by BarryThePenguin**
Resolves deprecation message according to postcss/postcss#487

### CODE REVIEW

**Comment by markgoodyear** [comment]
:+1: Been meaning to update this. It appears the travis build is failing, likely due to the `package.json` using the older version of PostCSS. Would you be able to bump to the latest version for the PR and I'll get this merged in.

**Comment by markgoodyear** [comment]
Closing due to inactivity. I've updated to work with PostCSS 5 and updated deps so tests pass.

**Comment by BarryThePenguin** [comment]
Ah! Sorry. I completely missed this. Thanks for the update, this is brilliant :+1:

**Comment by markgoodyear** [comment]
No problem @BarryThePenguin :smile:

**Pull request closed without merging**
